ewz_recaptcha:
    public_key:  6LfRf-cUAAAAADWjJQkZ5JLCPH729_mV4IKLZeLg
    private_key: 6LfRf-cUAAAAACfCYnubIj2FZLpBbLMX0Hoe0FN7
    # Not needed as "%kernel.default_locale%" is the default value for the locale key
    # locale_key:  %kernel.default_locale%
    locale_from_request: true
    enabled: false
    ajax: true
    api_host: recaptcha.net
    verify_host: true